import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import {
  B4_PRODUCT_IDENTIFIER,
  B4_AUDIO_AUTHORITY,
  createB4AudioInventory,
  validateB4AudioManifest,
} from '../src/app/b4-round-contract.js';
import {
  selectNativeAppComposition,
} from '../src/app/create-app-services.js';

test('B4Development selects the bounded Starter product on both native platforms', () => {
  for (const platform of ['ios', 'android']) {
    assert.deepEqual(
      selectNativeAppComposition({ buildMode: 'B4Development', platform }),
      {
        serviceMode: 'b4',
        productIdentifier: 'b4-starter-product',
        runtime: { isNativePlatform: true, platform },
      },
    );
  }
  assert.equal(B4_PRODUCT_IDENTIFIER, 'b4-starter-product');
});

test('normal native composition remains B2 and explicit B3 composition remains exact', () => {
  assert.deepEqual(
    selectNativeAppComposition({ buildMode: 'production', platform: 'android' }),
    { serviceMode: 'b2', runtime: null },
  );
  assert.deepEqual(
    selectNativeAppComposition({ buildMode: 'B3SandboxProof', platform: 'ios' }),
    {
      serviceMode: 'b3',
      runtime: {
        isNativePlatform: true,
        platform: 'ios',
        buildAuthority: {
          mode: 'B3SandboxProof',
          proofKind: 'physical-live',
          platform: 'ios',
          distribution: 'development',
          publicSandboxOrigin: 'https://b3-gateway.eugnel.uk',
          workerName: 'ks2-spelling-b3-sandbox',
        },
      },
    },
  );
});

test('B4 uses mode-baked web assets with the ordinary native wrappers', async () => {
  const [main, packageJson, iosScheme, android] = await Promise.all([
    readFile(new URL('../src/main.jsx', import.meta.url), 'utf8'),
    readFile(new URL('../package.json', import.meta.url), 'utf8'),
    readFile(
      new URL('../ios/App/App.xcodeproj/xcshareddata/xcschemes/KS2Spelling.xcscheme', import.meta.url),
      'utf8',
    ),
    readFile(new URL('../android/app/build.gradle', import.meta.url), 'utf8'),
  ]);
  assert.match(main, /buildMode:\s*import\.meta\.env\.MODE/u);
  assert.match(packageJson, /"build:b4-development":\s*"vite build --mode B4Development"/u);
  assert.match(
    packageJson,
    /"sync:b4-development":\s*"npm run build:b4-development && cap sync"/u,
  );
  assert.doesNotMatch(iosScheme, /B4Development/u);
  assert.doesNotMatch(android, /b4Development/u);
});

test('trace-derived B4 audio inventory rejects pending authority', () => {
  const inventory = createB4AudioInventory();
  assert.equal(inventory.length, 25);
  assert.equal(inventory.filter(({ kind }) => kind === 'word-natural').length, 5);
  assert.equal(inventory.filter(({ kind }) => kind === 'dictation-normal').length, 10);
  assert.equal(inventory.filter(({ kind }) => kind === 'dictation-slow').length, 10);
  assert.deepEqual(
    [B4_AUDIO_AUTHORITY.model, B4_AUDIO_AUTHORITY.voice, B4_AUDIO_AUTHORITY.responseFormat],
    ['gpt-4o-mini-tts', 'cedar', 'mp3'],
  );
  assert.equal(B4_AUDIO_AUTHORITY.backendGenerated, true);
  assert.equal(B4_AUDIO_AUTHORITY.runtimeGeneration, false);
  assert.equal(B4_AUDIO_AUTHORITY.runtimeProviderAccess, false);
  assert.equal(B4_AUDIO_AUTHORITY.b4Distribution, 'bundled-development-proof');
  assert.deepEqual(B4_AUDIO_AUTHORITY.forbiddenClientTts, [
    'Web SpeechSynthesis',
    'iOS AVSpeechSynthesizer',
    'Android TextToSpeech',
    'runtime network fallback',
  ]);
  assert.equal(
    B4_AUDIO_AUTHORITY.futureDisclosure,
    'Audio in this app is generated by AI, not spoken by a human.',
  );
  assert.throws(
    () => validateB4AudioManifest({ productIdentifier: B4_PRODUCT_IDENTIFIER, assets: inventory }),
    (error) => error?.code === 'b4_audio_authority_incomplete',
  );
});
