import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

import {
  B4_PRODUCT_IDENTIFIER,
  B4_AUDIO_AUTHORITY,
  B4_RUNTIME_ITEM_IDS,
  B4_SENTENCE_PROMPTS,
  createB4AudioInventory,
  loadB4SpellingCatalogue,
  validateB4AudioManifest,
} from '../src/app/b4-round-contract.js';
import {
  selectNativeAppComposition,
} from '../src/app/create-app-services.js';

test('B4Development selects the bounded Starter product on both native platforms', () => {
  for (const platform of ['ios', 'android']) {
    assert.deepEqual(
      selectNativeAppComposition({ buildMode: 'B4Development', platform }),
      {
        serviceMode: 'b4',
        productIdentifier: 'b4-starter-product',
        runtime: { isNativePlatform: true, platform },
      },
    );
  }
  assert.equal(B4_PRODUCT_IDENTIFIER, 'b4-starter-product');
});

test('normal native composition is the production product and explicit B3 remains exact', () => {
  assert.deepEqual(
    selectNativeAppComposition({ buildMode: 'production', platform: 'android' }),
    {
      serviceMode: 'product',
      productIdentifier: 'ks2-spelling-product',
      runtime: { isNativePlatform: true, platform: 'android' },
    },
  );
  assert.deepEqual(
    selectNativeAppComposition({ buildMode: 'B3SandboxProof', platform: 'ios' }),
    {
      serviceMode: 'b3',
      runtime: {
        isNativePlatform: true,
        platform: 'ios',
        buildAuthority: {
          mode: 'B3SandboxProof',
          proofKind: 'physical-live',
          platform: 'ios',
          distribution: 'development',
          publicSandboxOrigin: 'https://b3-gateway.eugnel.uk',
          workerName: 'ks2-spelling-b3-sandbox',
        },
      },
    },
  );
});

test('B4 uses mode-baked web assets with the ordinary native wrappers', async () => {
  const [main, packageJson, iosScheme, android, mountApp] = await Promise.all([
    readFile(new URL('../src/main.jsx', import.meta.url), 'utf8'),
    readFile(new URL('../package.json', import.meta.url), 'utf8'),
    readFile(
      new URL('../ios/App/App.xcodeproj/xcshareddata/xcschemes/KS2Spelling.xcscheme', import.meta.url),
      'utf8',
    ),
    readFile(new URL('../android/app/build.gradle', import.meta.url), 'utf8'),
    readFile(new URL('../src/app/mount-app.js', import.meta.url), 'utf8'),
  ]);
  assert.match(main, /buildMode:\s*import\.meta\.env\.MODE/u);
  assert.match(main, /mountApp\(/u);
  assert.match(main, /AppLoadingShell/u);
  assert.match(mountApp, /renderLoading\(\)/u);
  assert.match(
    mountApp,
    /Paint a lightweight shell before native service initialisation/u,
  );
  assert.match(packageJson, /"build:b4-development":\s*"vite build --mode B4Development"/u);
  assert.match(
    packageJson,
    /"sync:b4-development":\s*"npm run build:b4-development && cap sync"/u,
  );
  assert.doesNotMatch(iosScheme, /B4Development/u);
  assert.doesNotMatch(android, /b4Development/u);
});

test('trace-derived B4 audio inventory rejects pending authority', () => {
  const inventory = createB4AudioInventory();
  assert.equal(inventory.length, 25);
  assert.equal(inventory.filter(({ kind }) => kind === 'word-natural').length, 5);
  assert.equal(inventory.filter(({ kind }) => kind === 'dictation-normal').length, 10);
  assert.equal(inventory.filter(({ kind }) => kind === 'dictation-slow').length, 10);
  assert.deepEqual(
    [B4_AUDIO_AUTHORITY.engine, B4_AUDIO_AUTHORITY.engineVersion, B4_AUDIO_AUTHORITY.voice],
    ['piper-tts', '1.5.0', 'en_GB-cori-medium'],
  );
  assert.equal(B4_AUDIO_AUTHORITY.engineLicence, 'GPL-3.0-or-later');
  assert.equal(B4_AUDIO_AUTHORITY.voiceRights, 'public domain; permitted for any legal and ethical purpose');
  assert.equal(B4_AUDIO_AUTHORITY.outputFormat, 'wav-pcm-s16le-mono-22050hz');
  assert.equal(B4_AUDIO_AUTHORITY.backendGenerated, true);
  assert.equal(B4_AUDIO_AUTHORITY.runtimeGeneration, false);
  assert.equal(B4_AUDIO_AUTHORITY.runtimeProviderAccess, false);
  assert.equal(B4_AUDIO_AUTHORITY.b4Distribution, 'bundled-development-proof');
  assert.equal(B4_AUDIO_AUTHORITY.productionDistribution, 'server pack/local install');
  assert.deepEqual(B4_AUDIO_AUTHORITY.forbiddenClientTts, [
    'Web SpeechSynthesis',
    'iOS AVSpeechSynthesizer',
    'Android TextToSpeech',
    'runtime network fallback',
  ]);
  assert.equal(
    B4_AUDIO_AUTHORITY.futureDisclosure,
    'Audio in this app is generated by AI, not spoken by a human.',
  );
  assert.throws(
    () => validateB4AudioManifest({ productIdentifier: B4_PRODUCT_IDENTIFIER, assets: inventory }),
    (error) => error?.code === 'b4_audio_authority_incomplete',
  );
});

test('B4 content exposes only sentence prompts covered by its local audio manifest', () => {
  const catalogue = loadB4SpellingCatalogue();
  for (const runtimeItemId of B4_RUNTIME_ITEM_IDS) {
    const item = catalogue.items.find((candidate) => candidate.runtimeItemId === runtimeItemId);
    const expected = B4_SENTENCE_PROMPTS
      .filter((prompt) => prompt.runtimeItemId === runtimeItemId)
      .map((prompt) => prompt.sentence)
      .sort();
    assert.deepEqual(item.sentencePrompts.map(({ text }) => text).sort(), expected);
    assert.equal(item.sentencePrompts.length, 2);
  }
  assert.equal(catalogue.audio.requiredAssetCount, 680);
});
