export const SCHEMA_VERSION = 2;

export const SCHEMA_V2_STATEMENTS = Object.freeze([
  "CREATE TABLE app_entitlements (entitlement_id TEXT PRIMARY KEY, store TEXT NOT NULL CHECK (store IN ('apple', 'google')), product_id TEXT NOT NULL, state TEXT NOT NULL CHECK (state IN ('active', 'revoked')), sealed_refresh_handle TEXT NULL, refresh_handle_version INTEGER NULL, verified_at INTEGER NOT NULL CHECK (typeof(verified_at) = 'integer' AND verified_at >= 0), refreshed_at INTEGER NOT NULL CHECK (typeof(refreshed_at) = 'integer' AND refreshed_at >= 0), revocation_at INTEGER NULL CHECK (revocation_at IS NULL OR (typeof(revocation_at) = 'integer' AND revocation_at >= 0)), CHECK ((sealed_refresh_handle IS NULL AND refresh_handle_version IS NULL) OR (sealed_refresh_handle IS NOT NULL AND typeof(refresh_handle_version) = 'integer' AND refresh_handle_version > 0))) WITHOUT ROWID;",
  "CREATE TABLE transaction_journal (journal_id TEXT PRIMARY KEY, store TEXT NOT NULL CHECK (store IN ('apple', 'google')), product_id TEXT NOT NULL, store_transaction_id TEXT NULL, observation_state TEXT NOT NULL CHECK (observation_state IN ('pending', 'purchased', 'revoked')), processing_state TEXT NOT NULL CHECK (processing_state IN ('observed', 'verified', 'entitlement-committed', 'store-completion-pending', 'complete', 'rejected')), opaque_proof TEXT NULL, created_at INTEGER NOT NULL CHECK (typeof(created_at) = 'integer' AND created_at >= 0), updated_at INTEGER NOT NULL CHECK (typeof(updated_at) = 'integer' AND updated_at >= created_at), UNIQUE (store, store_transaction_id)) WITHOUT ROWID;",
  "CREATE TABLE installed_pack_versions (pack_id TEXT NOT NULL, version TEXT NOT NULL, manifest_sha256 TEXT NOT NULL, path_token TEXT NOT NULL, activation_marker_sha256 TEXT NOT NULL, state TEXT NOT NULL CHECK (state IN ('ready', 'retired')), installed_at INTEGER NOT NULL CHECK (typeof(installed_at) = 'integer' AND installed_at >= 0), PRIMARY KEY (pack_id, version)) WITHOUT ROWID;",
  "CREATE TABLE active_pack_versions (pack_id TEXT PRIMARY KEY, version TEXT NOT NULL, manifest_sha256 TEXT NOT NULL, path_token TEXT NOT NULL, activated_at INTEGER NOT NULL CHECK (typeof(activated_at) = 'integer' AND activated_at >= 0), FOREIGN KEY (pack_id, version) REFERENCES installed_pack_versions(pack_id, version)) WITHOUT ROWID;",
  "CREATE TABLE pack_download_jobs (job_id TEXT PRIMARY KEY, pack_id TEXT NOT NULL, version TEXT NOT NULL, manifest_sha256 TEXT NOT NULL, archive_name TEXT NOT NULL, archive_sha256 TEXT NOT NULL, expected_bytes INTEGER NOT NULL CHECK (typeof(expected_bytes) = 'integer' AND expected_bytes >= 0), completed_bytes INTEGER NOT NULL CHECK (typeof(completed_bytes) = 'integer' AND completed_bytes >= 0 AND completed_bytes <= expected_bytes), etag TEXT NULL, state TEXT NOT NULL CHECK (state IN ('queued', 'downloading', 'downloaded', 'extracting', 'ready', 'failed')), updated_at INTEGER NOT NULL CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0)) WITHOUT ROWID;",
  "CREATE TABLE pack_download_chunks (job_id TEXT NOT NULL, start_byte INTEGER NOT NULL CHECK (typeof(start_byte) = 'integer' AND start_byte >= 0), end_byte_exclusive INTEGER NOT NULL CHECK (typeof(end_byte_exclusive) = 'integer' AND end_byte_exclusive > start_byte), state TEXT NOT NULL CHECK (state IN ('pending', 'complete')), chunk_sha256 TEXT NULL, PRIMARY KEY (job_id, start_byte), FOREIGN KEY (job_id) REFERENCES pack_download_jobs(job_id) ON DELETE CASCADE) WITHOUT ROWID;",
]);
